---
services:
  adminer:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: adminer-oci8:local
    container_name: adminer
    networks:
      postgres_net:
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres-db
    volumes:
      - ./tns:/opt/oracle/instantclient_23_9/network/admin:ro
networks:
  postgres_net:
    driver: bridge
